/* Text to put at the beginning of the generated file. Probably a license. */

/* Generated with cbindgen:0.13.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct LDKConduit LDKConduit;

typedef struct LDKPeerHandshake LDKPeerHandshake;

typedef struct {
   uint8_t *data;
   uintptr_t length;
} LDKBufferResponse;

typedef struct {
   const uint8_t *data;
   uintptr_t length;
} LDKBufferArgument;

typedef struct {
   char *message;
   uintptr_t length;
} LDKError;

typedef struct {
   LDKBufferResponse *next_act;
   LDKConduit *conduit;
} LDKHandshakeResult;

void free_buffer(LDKBufferResponse *raw_buffer);

LDKBufferResponse *peer_conduit_decrypt(LDKConduit *conduit, const LDKBufferArgument *message, LDKError *error);

LDKPeerHandshake *peer_handshake_new_outbound(const uint8_t *private_key, const uint8_t *ephemeral_private_key, const uint8_t *remote_public_key);

LDKPeerHandshake *peer_handshake_new_inbound(const uint8_t *private_key, const uint8_t *ephemeral_private_key);

LDKHandshakeResult *peer_handshake_process_act(LDKPeerHandshake *peer, const LDKBufferArgument *act_data, LDKError *error);

/* Text to put at the end of the generated file */
